[package]
name = "ai-2048"
version = "0.1.0"
authors = ["Matthew Kennedy <kennedymj97@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
wasm-bindgen = "0.2"
# Ensure RNG works on wasm32-unknown-unknown by enabling JS entropy source
getrandom = { version = "0.2", features = ["js"] }
rayon = "1"
dashmap = "5"
ahash = "0.8"
indicatif = "0.17"
clap = { version = "4", features = ["derive"] }
crc32c = "0.6.8"
bytemuck = "1.23.2"
memmap2 = "0.9.7"
thiserror = "2.0.16"
anyhow = "1.0.99"
owo-colors = "4.2.2"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.21.0"
