name: Build and Deploy Docs

on:
  push:
    branches: [master]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/configure-pages@v5

      - name: Build documentation
        run: cargo doc --no-deps

      - name: Determine docs root (crate dir)
        id: docroot
        run: |
          CRATE=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].name' | sed 's/-/_/g')
          DOC_DIR="target/doc/${CRATE}"
          test -f "${DOC_DIR}/index.html" || (echo "index.html not found in ${DOC_DIR}"; ls -la target/doc; exit 1)
          echo "dir=${DOC_DIR}" >> "$GITHUB_OUTPUT"

      - name: Disable Jekyll (best practice for docs)
        run: touch "${{ steps.docroot.outputs.dir }}/.nojekyll"

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.docroot.outputs.dir }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
